/**
 * Multi-format Cookie Serializer & Parser
 */

export class CookieFormats {
  /**
   * Export to standard JSON
   */
  static toJSON(cookies) {
    return JSON.stringify(cookies, null, 2);
  }

  /**
   * Export to Netscape / wget / curl cookiefile format
   */
  static toNetscape(cookies) {
    const lines = [
      '# Netscape HTTP Cookie File',
      '# https://curl.se/docs/http-cookies.html',
      '# This file was generated by CookieNexus',
      '',
    ];

    for (const c of (cookies || [])) {
      if (!c || !c.name) continue;
      const rawDomain = c.domain || 'localhost';
      const isSubdomain = rawDomain.startsWith('.');
      const prefix = c.httpOnly ? '#HttpOnly_' : '';
      const domain = `${prefix}${rawDomain}`;
      const flag = isSubdomain ? 'TRUE' : 'FALSE';
      const path = c.path || '/';
      const secure = c.secure ? 'TRUE' : 'FALSE';
      const expiry = Math.floor(c.expirationDate || (Date.now() / 1000 + 86400 * 30));
      lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value || ''}`);
    }

    return lines.join('\n');
  }

  /**
   * Export to HTTP Header format: "name1=val1; name2=val2"
   */
  static toHeader(cookies) {
    return (cookies || []).filter(c => c && c.name).map(c => `${c.name}=${c.value || ''}`).join('; ');
  }

  /**
   * Export to Playwright `storageState.json` format
   */
  static toPlaywright(cookies, origins = []) {
    const playwrightCookies = (cookies || []).filter(c => c && c.name).map(c => {
      const s = (c.sameSite || 'Lax').toLowerCase();
      const sameSiteVal = s === 'strict' ? 'Strict' : s === 'none' ? 'None' : 'Lax';
      return {
        name: c.name,
        value: c.value || '',
        domain: c.domain || 'localhost',
        path: c.path || '/',
        expires: c.expirationDate || -1,
        httpOnly: !!c.httpOnly,
        secure: !!c.secure,
        sameSite: sameSiteVal,
      };
    });

    return JSON.stringify({
      cookies: playwrightCookies,
      origins: origins
    }, null, 2);
  }

  /**
   * Parse Netscape format string into CookieRecord array
   */
  static parseNetscape(text) {
    const lines = (text || '').split('\n');
    const cookies = [];

    for (const rawLine of lines) {
      let line = rawLine.trim();
      if (!line) continue;

      let isHttpOnly = false;
      if (line.startsWith('#HttpOnly_')) {
        isHttpOnly = true;
        line = line.substring('#HttpOnly_'.length);
      } else if (line.startsWith('#')) {
        continue;
      }

      const parts = line.split('\t');
      if (parts.length >= 7) {
        cookies.push({
          domain: parts[0],
          path: parts[2] || '/',
          secure: parts[3].toUpperCase() === 'TRUE',
          expirationDate: parseInt(parts[4], 10) || null,
          name: parts[5],
          value: parts[6] || '',
          httpOnly: isHttpOnly,
          sameSite: 'Lax',
          session: !parts[4] || parts[4] === '0',
          updatedAt: Date.now(),
        });
      }
    }
    return cookies;
  }

  /**
   * Export to cURL command string
   */
  static toCurl(cookies, url = 'https://example.com') {
    const headerStr = CookieFormats.toHeader(cookies);
    return `curl -b "${headerStr}" "${url}"`;
  }

  /**
   * Parse HTTP Cookie Header string into CookieRecord array
   */
  static parseHeader(headerStr, domain = 'localhost') {
    if (!headerStr) return [];
    let cleanStr = headerStr.trim();
    if (cleanStr.toLowerCase().startsWith('cookie:')) {
      cleanStr = cleanStr.substring('cookie:'.length).trim();
    }
    const cleanDomain = domain.replace(/^\./, '');
    const pairs = cleanStr.split(';');
    const cookies = [];

    for (const pair of pairs) {
      const idx = pair.indexOf('=');
      if (idx === -1) continue;
      const name = pair.slice(0, idx).trim();
      const value = pair.slice(idx + 1).trim();
      if (!name) continue;

      cookies.push({
        domain: cleanDomain,
        name,
        value,
        path: '/',
        secure: true,
        httpOnly: false,
        sameSite: 'Lax',
        session: true,
        updatedAt: Date.now(),
      });
    }
    return cookies;
  }

  /**
   * Parse single or multiline Set-Cookie response header string into CookieRecord array
   */
  static parseSetCookie(setCookieStr, defaultDomain = 'localhost') {
    if (!setCookieStr) return null;
    let cleanStr = setCookieStr.trim();
    if (cleanStr.toLowerCase().startsWith('set-cookie:')) {
      cleanStr = cleanStr.substring('set-cookie:'.length).trim();
    }
    const parts = cleanStr.split(';').map(p => p.trim());
    if (parts.length === 0) return null;

    const firstPair = parts[0];
    const eqIdx = firstPair.indexOf('=');
    if (eqIdx === -1) return null;

    const name = firstPair.slice(0, eqIdx).trim();
    const value = firstPair.slice(eqIdx + 1).trim();

    let domain = defaultDomain;
    let path = '/';
    let secure = false;
    let httpOnly = false;
    let sameSite = 'Lax';
    let expirationDate = null;
    let session = true;

    for (let i = 1; i < parts.length; i++) {
      const part = parts[i];
      const lower = part.toLowerCase();
      if (lower === 'secure') {
        secure = true;
      } else if (lower === 'httponly') {
        httpOnly = true;
      } else if (lower.startsWith('samesite=')) {
        const val = part.slice(9).trim().toLowerCase();
        sameSite = val === 'strict' ? 'Strict' : val === 'none' ? 'None' : 'Lax';
      } else if (lower.startsWith('domain=')) {
        domain = part.slice(7).trim();
      } else if (lower.startsWith('path=')) {
        path = part.slice(5).trim() || '/';
      } else if (lower.startsWith('expires=')) {
        const expiresStr = part.slice(8).trim();
        const parsedTime = Date.parse(expiresStr);
        if (!isNaN(parsedTime)) {
          expirationDate = Math.floor(parsedTime / 1000);
          session = false;
        }
      } else if (lower.startsWith('max-age=')) {
        const maxAgeSec = parseInt(part.slice(8).trim(), 10);
        if (!isNaN(maxAgeSec)) {
          expirationDate = Math.floor(Date.now() / 1000 + maxAgeSec);
          session = false;
        }
      }
    }

    return {
      domain,
      name,
      value,
      path,
      secure,
      httpOnly,
      sameSite,
      expirationDate,
      session,
      updatedAt: Date.now(),
    };
  }

  /**
   * Intelligently detects and parses any raw cookie input format:
   * JSON, Netscape, Set-Cookie lines, cURL command, or raw Cookie Header.
   */
  static parseAny(rawText, defaultDomain = 'localhost') {
    if (!rawText || !rawText.trim()) return [];
    const text = rawText.trim();

    // 1. Standard JSON (Array or Playwright storageState / CookieNexus envelope)
    if (text.startsWith('[') || text.startsWith('{')) {
      try {
        const parsed = JSON.parse(text);
        let list = null;
        if (Array.isArray(parsed)) list = parsed;
        else if (parsed.cookies && Array.isArray(parsed.cookies)) list = parsed.cookies;
        else if (parsed.cookie) list = [parsed.cookie];

        if (list) {
          return list.map(c => {
            const exp = c.expirationDate !== undefined ? c.expirationDate : (c.expires && c.expires > 0 ? c.expires : undefined);
            return {
              ...c,
              expirationDate: exp,
              path: c.path || '/',
              domain: c.domain || defaultDomain,
            };
          });
        }
      } catch (e) {}
    }

    // 2. Netscape format (contains tabs or #HttpOnly_ / # Netscape header)
    if (text.includes('\t') || text.includes('#HttpOnly_') || text.includes('# Netscape')) {
      const netscape = CookieFormats.parseNetscape(text);
      if (netscape.length > 0) return netscape;
    }

    // 3. cURL command (e.g. `curl -b "..." ...` or `curl -H "Cookie: ..." ...`)
    if (text.startsWith('curl ') || text.includes(' -b ') || text.includes(' --cookie ') || text.includes('Cookie:')) {
      const bMatch = text.match(/(?:-b|--cookie)\s+["']([^"']+)["']/i);
      if (bMatch && bMatch[1]) {
        return CookieFormats.parseHeader(bMatch[1], defaultDomain);
      }
      const hMatch = text.match(/-H\s+["']Cookie:\s*([^"']+)["']/i);
      if (hMatch && hMatch[1]) {
        return CookieFormats.parseHeader(hMatch[1], defaultDomain);
      }
    }

    // 4. Multiple or single Set-Cookie lines
    const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
    const isSetCookieList = lines.every(l => l.toLowerCase().startsWith('set-cookie:') || l.includes('expires=') || l.includes('max-age=') || l.includes('samesite='));
    if (isSetCookieList) {
      const results = [];
      for (const line of lines) {
        const sc = CookieFormats.parseSetCookie(line, defaultDomain);
        if (sc) results.push(sc);
      }
      if (results.length > 0) return results;
    }

    // 5. Fallback: parse as standard Cookie Header
    return CookieFormats.parseHeader(text, defaultDomain);
  }
}
