/**
 * Multi-format Cookie Serializer & Parser
 */

export class CookieFormats {
  /**
   * Export to standard JSON
   */
  static toJSON(cookies) {
    return JSON.stringify(cookies, null, 2);
  }

  /**
   * Export to Netscape / wget / curl cookiefile format
   */
  static toNetscape(cookies) {
    const lines = [
      '# Netscape HTTP Cookie File',
      '# https://curl.se/docs/http-cookies.html',
      '# This file was generated by CookieNexus',
      '',
    ];

    for (const c of cookies) {
      const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
      const flag = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = c.path || '/';
      const secure = c.secure ? 'TRUE' : 'FALSE';
      const expiry = Math.floor(c.expirationDate || (Date.now() / 1000 + 86400 * 30));
      lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
    }

    return lines.join('\n');
  }

  /**
   * Export to HTTP Header format: "name1=val1; name2=val2"
   */
  static toHeader(cookies) {
    return cookies.map(c => `${c.name}=${c.value}`).join('; ');
  }

  /**
   * Export to Playwright `storageState.json` format
   */
  static toPlaywright(cookies, origins = []) {
    const playwrightCookies = cookies.map(c => ({
      name: c.name,
      value: c.value,
      domain: c.domain,
      path: c.path,
      expires: c.expirationDate || -1,
      httpOnly: !!c.httpOnly,
      secure: !!c.secure,
      sameSite: c.sameSite === 'Strict' ? 'Strict' : c.sameSite === 'Lax' ? 'Lax' : 'None',
    }));

    return JSON.stringify({
      cookies: playwrightCookies,
      origins: origins
    }, null, 2);
  }

  /**
   * Parse Netscape format string into CookieRecord array
   */
  static parseNetscape(text) {
    const lines = text.split('\n');
    const cookies = [];

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line || line.startsWith('#')) continue;

      const parts = line.split('\t');
      if (parts.length >= 7) {
        cookies.push({
          domain: parts[0],
          path: parts[2],
          secure: parts[3].toUpperCase() === 'TRUE',
          expirationDate: parseInt(parts[4], 10),
          name: parts[5],
          value: parts[6],
          httpOnly: false,
          sameSite: 'Lax',
          session: false,
          updatedAt: Date.now(),
        });
      }
    }
    return cookies;
  }
}
