/**
 * Multi-format Cookie Serializer & Parser
 */

export class CookieFormats {
  /**
   * Export to standard JSON
   */
  static toJSON(cookies) {
    return JSON.stringify(cookies, null, 2);
  }

  /**
   * Export to Netscape / wget / curl cookiefile format
   */
  static toNetscape(cookies) {
    const lines = [
      '# Netscape HTTP Cookie File',
      '# https://curl.se/docs/http-cookies.html',
      '# This file was generated by CookieNexus',
      '',
    ];

    for (const c of (cookies || [])) {
      if (!c || !c.name) continue;
      const rawDomain = c.domain || 'localhost';
      const isSubdomain = rawDomain.startsWith('.');
      const prefix = c.httpOnly ? '#HttpOnly_' : '';
      const domain = `${prefix}${rawDomain}`;
      const flag = isSubdomain ? 'TRUE' : 'FALSE';
      const path = c.path || '/';
      const secure = c.secure ? 'TRUE' : 'FALSE';
      const expiry = Math.floor(c.expirationDate || (Date.now() / 1000 + 86400 * 30));
      lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value || ''}`);
    }

    return lines.join('\n');
  }

  /**
   * Export to HTTP Header format: "name1=val1; name2=val2"
   */
  static toHeader(cookies) {
    return (cookies || []).filter(c => c && c.name).map(c => `${c.name}=${c.value || ''}`).join('; ');
  }

  /**
   * Export to Playwright `storageState.json` format
   */
  static toPlaywright(cookies, origins = []) {
    const playwrightCookies = (cookies || []).filter(c => c && c.name).map(c => {
      const s = (c.sameSite || 'Lax').toLowerCase();
      const sameSiteVal = s === 'strict' ? 'Strict' : s === 'none' ? 'None' : 'Lax';
      return {
        name: c.name,
        value: c.value || '',
        domain: c.domain || 'localhost',
        path: c.path || '/',
        expires: c.expirationDate || -1,
        httpOnly: !!c.httpOnly,
        secure: !!c.secure,
        sameSite: sameSiteVal,
      };
    });

    return JSON.stringify({
      cookies: playwrightCookies,
      origins: origins
    }, null, 2);
  }

  /**
   * Parse Netscape format string into CookieRecord array
   */
  static parseNetscape(text) {
    const lines = (text || '').split('\n');
    const cookies = [];

    for (const rawLine of lines) {
      let line = rawLine.trim();
      if (!line) continue;

      let isHttpOnly = false;
      if (line.startsWith('#HttpOnly_')) {
        isHttpOnly = true;
        line = line.substring('#HttpOnly_'.length);
      } else if (line.startsWith('#')) {
        continue;
      }

      const parts = line.split('\t');
      if (parts.length >= 7) {
        cookies.push({
          domain: parts[0],
          path: parts[2] || '/',
          secure: parts[3].toUpperCase() === 'TRUE',
          expirationDate: parseInt(parts[4], 10) || null,
          name: parts[5],
          value: parts[6] || '',
          httpOnly: isHttpOnly,
          sameSite: 'Lax',
          session: !parts[4] || parts[4] === '0',
          updatedAt: Date.now(),
        });
      }
    }
    return cookies;
  }

  /**
   * Export to cURL command string
   */
  static toCurl(cookies, url = 'https://example.com') {
    const headerStr = CookieFormats.toHeader(cookies);
    return `curl -b "${headerStr}" "${url}"`;
  }

  /**
   * Parse HTTP Cookie Header string into CookieRecord array
   */
  static parseHeader(headerStr, domain = 'localhost') {
    if (!headerStr) return [];
    const cleanDomain = domain.replace(/^\./, '');
    const pairs = headerStr.split(';');
    const cookies = [];

    for (const pair of pairs) {
      const idx = pair.indexOf('=');
      if (idx === -1) continue;
      const name = pair.slice(0, idx).trim();
      const value = pair.slice(idx + 1).trim();
      if (!name) continue;

      cookies.push({
        domain: cleanDomain,
        name,
        value,
        path: '/',
        secure: true,
        httpOnly: false,
        sameSite: 'Lax',
        session: true,
        updatedAt: Date.now(),
      });
    }
    return cookies;
  }

  /**
   * Parse single Set-Cookie response header string into CookieRecord
   */
  static parseSetCookie(setCookieStr, defaultDomain = 'localhost') {
    if (!setCookieStr) return null;
    const parts = setCookieStr.split(';').map(p => p.trim());
    if (parts.length === 0) return null;

    const firstPair = parts[0];
    const eqIdx = firstPair.indexOf('=');
    if (eqIdx === -1) return null;

    const name = firstPair.slice(0, eqIdx).trim();
    const value = firstPair.slice(eqIdx + 1).trim();

    let domain = defaultDomain;
    let path = '/';
    let secure = false;
    let httpOnly = false;
    let sameSite = 'Lax';
    let expirationDate = null;
    let session = true;

    for (let i = 1; i < parts.length; i++) {
      const part = parts[i];
      const lower = part.toLowerCase();
      if (lower === 'secure') {
        secure = true;
      } else if (lower === 'httponly') {
        httpOnly = true;
      } else if (lower.startsWith('samesite=')) {
        const val = part.slice(9).trim().toLowerCase();
        sameSite = val === 'strict' ? 'Strict' : val === 'none' ? 'None' : 'Lax';
      } else if (lower.startsWith('domain=')) {
        domain = part.slice(7).trim();
      } else if (lower.startsWith('path=')) {
        path = part.slice(5).trim() || '/';
      } else if (lower.startsWith('expires=')) {
        const expiresStr = part.slice(8).trim();
        const parsedTime = Date.parse(expiresStr);
        if (!isNaN(parsedTime)) {
          expirationDate = Math.floor(parsedTime / 1000);
          session = false;
        }
      } else if (lower.startsWith('max-age=')) {
        const maxAgeSec = parseInt(part.slice(8).trim(), 10);
        if (!isNaN(maxAgeSec)) {
          expirationDate = Math.floor(Date.now() / 1000 + maxAgeSec);
          session = false;
        }
      }
    }

    return {
      domain,
      name,
      value,
      path,
      secure,
      httpOnly,
      sameSite,
      expirationDate,
      session,
      updatedAt: Date.now(),
    };
  }
}
